### ISSUE TITLE
How to apply this research on music?

### ISSUE THREAD

**Issue by shoegazerstella** [beausievers/supramodal_arousal#1]
Hello @beausievers and thank you for sharing this very interesting research.

I am trying to apply your observations on my dataset.
I have a collection of songs that were manually tagged with valence/arousal values and I am computing the spectral centroid of the audio as in [here](https://github.com/beausievers/supramodal_arousal/blob/master/analysis/spectral_centroid.py), then I am retaining some statistics on the resulting vector such as mean, std and variance.

I would like to share with you some doubts/questions I have on how to proceed:
- the audio have different durations (~2-3minutes), I was thinking to analyze only 30 seconds from its central part. This is already a big assumption as the spectral centroid varies a lot with time.
- once I have my spectral centroid vectors, which can be, in your opinion, the best statistics to compute in order for this to be as close as possible to the tagged arousal value?

I saw in your paper that you computed the mean of the SC on 1.5 seconds long audio files. Any idea on how this can be applied on longer audio segments?

**Comment by beausievers** [comment]
Thanks for your interest!

The analysis in the paper depends on two assumptions: (1) that the emotional arousal of an expression is stationary, and (2) that an expression makes relatively more use of low-level features to communicate arousal, versus using semantics. If both of these things are more-or-less true, I think taking the mean SC of each expression is a reasonable place to start.

Importantly, natural music violates both of those assumptions: there's lots of variation in arousal over time, and music uses both low-level features _and_ semantics to communicate emotion content. So while I do expect that the SC will be informative, it will probably explain a smaller proportion of variance in arousal in natural music than it does in the expressions analyzed in the paper. 

Please let me know what you find!

**Comment by shoegazerstella** [comment]
Thanks a lot for your quick reply.

For now, I was computing the mean error on sc_mean, sc_std and sc_var on 100 data I have. I am just computing the mean of the difference between my 'real' arousal values and the 3 spectral centroid statistics.
Interestingly, the error on the mean value of the spectral centroid is very low compared to the other two.

```
('error_mean', 4.9242876366160004)
('error_std', 15.851686608038001)
('error_var', 32.588186522829403)
``` 

I will try to think more on this and let you know if I come up with something interesting.
